server:
  port: 8081

spring:
  application:
    name: consumer
  kafka:
    consumer:
      auto-offset-reset: earliest  # читать с самого начала топика
      group-id: weather-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[spring.json.value.default.type]": com.example.consumer.model.WeatherInfo
        "[spring.json.trusted.packages]": "com.example.consumer.model"
        "[spring.json.use.type.headers]": false
    listener:
      missing-topics-fatal: false
