spring:
  application:
    name: producer
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # для JSON
      properties:
        "[spring.json.value.default.type]": com.example.consumer.model.WeatherInfo
        "[spring.json.trusted.packages]": "com.example.consumer.model"
        "[spring.json.date-format]": "yyyy-MM-dd" 

server:
  port: 8080

